### ISSUE TITLE
Self installing yaourt

### ISSUE THREAD

**Issue by pree** [niklas-heer/dotbot-yaourt#2]
It would be pretty neat if the plugins installs yaourt, if it is not installed on the system allready

**Comment by niklas-heer** [comment]
@pree thank you for getting involved. It's always nice to get some feedback. :)

One topic we should discuss first is if this tool should also do that. 
I'm a believer in the Unix philosophy "Do One Thing and Do It Well". I also think developers more often than not try to reinvent the wheel. Which raises the question if this should be added at all. 
My personal opinion is that the best option to install yaourt is to put it into the dotbot "script section" and use already great scripts like [this](https://github.com/Phifo/yaourt/blob/master/yaourt-install).

What do you think?

**Comment by pree** [comment]
Hey @niklas-heer ,

I played around a lot with the yaourt plugin the last couple of days and didn't had that great understanding of dotbot before. I totally agree that this does indeed not need to be done by this plugin. I was just thinking of "it would be need to run this on a clean installed archlinux and it would manage that for me", but realized that quickly ends up to not knowing, what your own stuff really does. 
BTW, while tinkering around I noticed, that the plugin often doesn't know what to do, like when a package needs to be replaced (example: when installing `powerline-fonts-git` when `ttf-hack` is already on the system), but that is for another Issue

**Comment by niklas-heer** [comment]
Hey @pree ,

I'm glad that I could help you. I'm closing this issue now.
The second thing you mention is kind of weird, but maybe it is an issue of `yaourt` itself.
Because this plugin only helps you to maintain a list of applications you want to install and then triggers `yaourt` to handle the install.
So maybe you can have a look into [`yaourt`s issues](https://github.com/archlinuxfr/yaourt/issues) if someone has the same problem.
